apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: stackforge
data:
  NODE_ENV: production
  PORT: "4000"
  TOTP_ISSUER: SpeaksyAuth
  TOTP_DIGITS: "6"
  TOTP_STEP: "30"
  JWT_EXPIRATION: 7d
  REDIS_HOST: redis-svc
  REDIS_PORT: "6379"