apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackforge
  namespace: argocd
  labels:
    app: stackforge
    managed-by: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Anuj8215/StackForge.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: stackforge

  syncPolicy:
    automated:
      prune: true       # delete K8s resources removed from Git
      selfHeal: true    # revert manual changes made outside Git
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
